export const basketConstants = {
    ADD_PRODUCT_TO_BASKET: 'ADD_PRODUCT_TO_BASKET',
    REMOVE_PRODUCT_FROM_BASKET: 'REMOVE_PRODUCT_FROM_BASKET',
    CLEAR_BASKET: 'CLEAR_BASKET',
    LOAD_BASKET_REQUEST: 'LOAD_BASKET_REQUEST',
    LOAD_BASKET_SUCCESS: 'LOAD_BASKET_SUCCESS',
    LOAD_BASKET_FAILURE: 'LOAD_BASKET_FAILURE',
    CHANGE_PRODUCT_QUANTITY: 'CHANGE_PRODUCT_QUANTITY',
}