export const bucketConstants = {
    ADD_PRODUCT_TO_BUCKET: 'ADD_PRODUCT_TO_BUCKET',
    REMOVE_PRODUCT_FROM_BUCKET: 'REMOVE_PRODUCT_FROM_BUCKET',
    CLEAR_BUCKET: 'CLEAR_BUCKET',
    LOAD_BUCKET_REQUEST: 'LOAD_BUCKET_REQUEST',
    LOAD_BUCKET_SUCCESS: 'LOAD_BUCKET_SUCCESS',
    LOAD_BUCKET_FAILURE: 'LOAD_BUCKET_FAILURE',
}