

export const categoryConstant = {
    CATEGORY_ALL_GET_REQUEST: 'CATEGORY_ALL_GET_REQUEST',
    CATEGORY_ALL_GET_SUCCESS: 'CATEGORY_ALL_GET_SUCCESS',
    CATEGORY_ALL_GET_FAILURE: 'CATEGORY_ALL_GET_FAILURE'
}