

export const deliveryConstants = {
    GET_ALL_DELIVERY_REQUEST: 'GET_ALL_DELIVERY_REQUEST',
    GET_ALL_DELIVERY_SUCCESS: 'GET_ALL_DELIVERY_SUCCESS',
    GET_ALL_DELIVERY_FAILURE: 'GET_ALL_DELIVERY_FAILURE',
}