
export const productConstants = {
    PRODUCTS_GET_ALL_REQUEST: 'PRODUCTS_GET_ALL_REQUEST',
    PRODUCTS_GET_ALL_SUCCESS: 'PRODUCTS_GET_ALL_SUCCESS',
    PRODUCTS_GET_ALL_FAILURE: 'PRODUCTS_GET_ALL_FAILURE',
    PRODUCTS_GET_IN_CATEGORY_REQUEST: 'PRODUCTS_GET_IN_CATEGORY_REQUEST',
    PRODUCTS_GET_IN_CATEGORY_SUCCESS: 'PRODUCTS_GET_IN_CATEGORY_SUCCESS',
    PRODUCTS_GET_IN_CATEGORY_FAILURE: 'PRODUCTS_GET_IN_CATEGORY_FAILURE',
}
