

export const userConstants = {
    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    SIGNIN_USER_REQUEST: 'SIGNIN_USER_REQUEST',
    SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
    SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
    ACTIVE_USER_REQUEST: 'ACTIVE_USER_REQUEST',
    ACTIVE_USER_SUCCESS: 'ACTIVE_USER_SUCCESS',
    ACTIVE_USER_FAILURE: 'ACTIVE_USER_FAILURE',
}